"""Test cases for the hierarchical file system.

One idea per case. The cases that matter most here are the ones that span levels:
a grant that has to travel with a moved directory, a link that has to be followed
mid-path by every operation written two levels earlier. A flat map of path strings
clears level 1 comfortably and then loses to those.
"""

from __future__ import annotations

from harness.expect import Exactly
from harness.model import case, op

# ==========================================================================
# Level 1
# ==========================================================================

LEVEL_1 = [
    case(
        "l1_mkdir_create_read",
        1,
        [
            op("MKDIR", "/docs", ret=True),
            op("CREATE_FILE", "/docs/notes.txt", "hello", ret=True),
            op("READ_FILE", "/docs/notes.txt", ret="hello"),
            op("READ_FILE", "/docs", ret=None, why="a directory is not a file"),
            op("LS", "/docs", ret=["notes.txt"], why="child names, not full paths"),
        ],
        tags=["basics"],
        visible=True,
        doc="Make a directory, put a file in it, read it back.",
    ),
    case(
        "l1_parent_must_exist",
        1,
        [
            op("MKDIR", "/a/b", ret=False, why="/a does not exist yet"),
            op("CREATE_FILE", "/a/f.txt", "x", ret=False),
            op("LS", "/a", ret=[], why="the refused operations created nothing"),
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a/b", ret=True),
        ],
        tags=["basics", "paths", "rejection"],
        visible=True,
        doc="Intermediate directories are never created for you.",
    ),
    case(
        "l1_ls_of_a_file_is_its_own_name",
        1,
        [
            op("CREATE_FILE", "/readme.md", "read me", ret=True),
            op("LS", "/readme.md", ret=["readme.md"], why="LS of a file is that file"),
            op("LS", "/", ret=["readme.md"]),
            op("LS", "/nope", ret=[]),
        ],
        tags=["basics", "listing", "edge-values"],
        visible=True,
        doc="LS of a file returns the file's own name, not its contents.",
    ),
    case(
        "l1_ls_is_lexicographic",
        1,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/b.txt", "1", ret=True),
            op("CREATE_FILE", "/d/a10", "2", ret=True),
            op("CREATE_FILE", "/d/a2", "3", ret=True),
            op("MKDIR", "/d/C", ret=True),
            op(
                "LS",
                "/d",
                ret=["C", "a10", "a2", "b.txt"],
                why="string order: capitals first, and a10 before a2",
            ),
        ],
        tags=["listing", "ordering"],
        visible=True,
        doc="Children come back in string order, files and directories together.",
    ),
    case(
        "l1_duplicate_names_are_rejected",
        1,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a", ret=False),
            op("CREATE_FILE", "/a", "x", ret=False, why="a directory holds that name"),
            op("CREATE_FILE", "/f", "1", ret=True),
            op("CREATE_FILE", "/f", "2", ret=False),
            op("MKDIR", "/f", ret=False),
            op("READ_FILE", "/f", ret="1", why="the rejected create must not overwrite"),
        ],
        tags=["basics", "rejection"],
    ),
    case(
        "l1_root_already_exists",
        1,
        [
            op("MKDIR", "/", ret=False),
            op("CREATE_FILE", "/", "x", ret=False),
            op("LS", "/", ret=[]),
        ],
        tags=["edge-values", "rejection"],
    ),
    case(
        "l1_empty_content_is_a_value",
        1,
        [
            op("CREATE_FILE", "/e", "", ret=True),
            op(
                "READ_FILE",
                "/e",
                ret=Exactly(""),
                why='"" is content; None would mean there is no file',
            ),
            op("LS", "/", ret=["e"]),
        ],
        tags=["basics", "edge-values"],
    ),
    case(
        "l1_names_are_case_sensitive",
        1,
        [
            op("MKDIR", "/A", ret=True),
            op("MKDIR", "/a", ret=True),
            op("CREATE_FILE", "/A/x", "upper", ret=True),
            op("CREATE_FILE", "/a/x", "lower", ret=True),
            op("READ_FILE", "/A/x", ret="upper"),
            op("READ_FILE", "/a/x", ret="lower"),
        ],
        tags=["basics", "edge-values"],
    ),
    case(
        "l1_deep_nesting",
        1,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a/b", ret=True),
            op("MKDIR", "/a/b/c", ret=True),
            op("CREATE_FILE", "/a/b/c/d.txt", "deep", ret=True),
            op("READ_FILE", "/a/b/c/d.txt", ret="deep"),
            op("LS", "/a/b", ret=["c"]),
            op("LS", "/a/b/c", ret=["d.txt"]),
        ],
        tags=["basics", "nesting"],
    ),
    case(
        "l1_a_file_cannot_hold_children",
        1,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("MKDIR", "/f/d", ret=False, why="the parent must be a directory"),
            op("CREATE_FILE", "/f/g", "y", ret=False),
            op("READ_FILE", "/f/g", ret=None),
            op("READ_FILE", "/f", ret="x"),
        ],
        tags=["paths", "rejection"],
    ),
    case(
        "l1_siblings_are_independent",
        1,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/a", "1", ret=True),
            op("CREATE_FILE", "/d/b", "2", ret=True),
            op("CREATE_FILE", "/c", "3", ret=True),
            op("READ_FILE", "/d/a", ret="1"),
            op("READ_FILE", "/d/b", ret="2"),
            op("READ_FILE", "/c", ret="3"),
            op("LS", "/", ret=["c", "d"]),
        ],
        tags=["basics"],
    ),
    case(
        "l1_missing_paths_read_as_nothing",
        1,
        [
            op("READ_FILE", "/nope", ret=None),
            op("LS", "/nope", ret=[]),
            op("MKDIR", "/a", ret=True),
            op("READ_FILE", "/a/nope", ret=None),
            op("LS", "/a/nope", ret=[]),
        ],
        tags=["basics", "edge-values"],
    ),
    case(
        "l1_similar_names_are_distinct",
        1,
        [
            op("MKDIR", "/ab", ret=True),
            op("MKDIR", "/a", ret=True),
            op("CREATE_FILE", "/ab/x", "in-ab", ret=True),
            op("CREATE_FILE", "/a/x", "in-a", ret=True),
            op("LS", "/a", ret=["x"]),
            op("READ_FILE", "/ab/x", ret="in-ab"),
            op("READ_FILE", "/a/x", ret="in-a"),
        ],
        tags=["paths", "edge-values"],
    ),
]


# ==========================================================================
# Level 2
# ==========================================================================

LEVEL_2 = [
    case(
        "l2_rm_counts_the_files_in_the_subtree",
        2,
        [
            op("MKDIR", "/d", ret=True),
            op("MKDIR", "/d/e", ret=True),
            op("CREATE_FILE", "/d/a", "1", ret=True),
            op("CREATE_FILE", "/d/e/b", "2", ret=True),
            op("CREATE_FILE", "/keep", "3", ret=True),
            op("RM", "/d", ret=2, why="two files; the directories are not counted"),
            op("LS", "/", ret=["keep"]),
            op("READ_FILE", "/d/a", ret=None),
            op("RM", "/nope", ret=0),
        ],
        tags=["remove", "subtree"],
        visible=True,
        doc="RM takes the whole subtree and reports how many files went with it.",
    ),
    case(
        "l2_rm_of_an_empty_directory_returns_zero",
        2,
        [
            op("MKDIR", "/empty", ret=True),
            op("RM", "/empty", ret=0, why="no files were inside, but it is gone"),
            op("LS", "/", ret=[]),
            op("MKDIR", "/empty", ret=True, why="the name is free again"),
        ],
        tags=["remove", "edge-values"],
        visible=True,
        doc="A removal that reports 0 still happened.",
    ),
    case(
        "l2_mv_moves_a_whole_subtree",
        2,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/b", ret=True),
            op("MKDIR", "/a/inner", ret=True),
            op("CREATE_FILE", "/a/inner/f", "deep", ret=True),
            op("MV", "/a", "/b/a", ret=True),
            op("READ_FILE", "/b/a/inner/f", ret="deep"),
            op("LS", "/", ret=["b"]),
            op("READ_FILE", "/a/inner/f", ret=None),
        ],
        tags=["move", "subtree"],
        visible=True,
        doc="Everything beneath the source comes with it.",
    ),
    case(
        "l2_a_directory_cannot_move_inside_itself",
        2,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a/b", ret=True),
            op("MV", "/a", "/a/b/a", ret=False, why="the destination is inside the source"),
            op("MV", "/a", "/a", ret=False),
            op("LS", "/a", ret=["b"], why="the refused moves changed nothing"),
            op("LS", "/", ret=["a"]),
        ],
        tags=["move", "cycles", "rejection"],
        visible=True,
        doc="A directory cannot be moved into its own subtree.",
    ),
    case(
        "l2_find_returns_full_paths",
        2,
        [
            op("MKDIR", "/x", ret=True),
            op("MKDIR", "/x/y", ret=True),
            op("MKDIR", "/z", ret=True),
            op("CREATE_FILE", "/x/t", "1", ret=True),
            op("CREATE_FILE", "/x/y/t", "2", ret=True),
            op("CREATE_FILE", "/z/t", "3", ret=True),
            op("FIND", "/", "t", ret=["/x/t", "/x/y/t", "/z/t"]),
            op("FIND", "/x", "t", ret=["/x/t", "/x/y/t"]),
            op("FIND", "/", "nope", ret=[]),
        ],
        tags=["search", "ordering"],
        visible=True,
        doc="FIND returns full paths, in string order, from anywhere below the start.",
    ),
    case(
        "l2_find_matches_directories_and_the_start_path",
        2,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a/a", ret=True),
            op("CREATE_FILE", "/a/a/a", "x", ret=True),
            op("FIND", "/", "a", ret=["/a", "/a/a", "/a/a/a"]),
            op(
                "FIND",
                "/a",
                "a",
                ret=["/a", "/a/a", "/a/a/a"],
                why="the start path counts if its own name matches",
            ),
        ],
        tags=["search"],
        visible=True,
        doc="Directories match too, and so does the path you started from.",
    ),
    case(
        "l2_mv_will_not_overwrite",
        2,
        [
            op("CREATE_FILE", "/a", "A", ret=True),
            op("CREATE_FILE", "/b", "B", ret=True),
            op("MV", "/a", "/b", ret=False),
            op("READ_FILE", "/a", ret="A"),
            op("READ_FILE", "/b", ret="B"),
        ],
        tags=["move", "rejection"],
    ),
    case(
        "l2_mv_needs_a_real_source_and_an_existing_dest_parent",
        2,
        [
            op("CREATE_FILE", "/a", "A", ret=True),
            op("MV", "/a", "/nope/a", ret=False),
            op("MV", "/nothing", "/b", ret=False),
            op("READ_FILE", "/a", ret="A"),
            op("LS", "/", ret=["a"]),
        ],
        tags=["move", "rejection", "paths"],
    ),
    case(
        "l2_mv_renames_within_the_same_parent",
        2,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/old", "x", ret=True),
            op("MV", "/d/old", "/d/new", ret=True),
            op("READ_FILE", "/d/new", ret="x"),
            op("READ_FILE", "/d/old", ret=None),
            op("LS", "/d", ret=["new"]),
        ],
        tags=["move"],
    ),
    case(
        "l2_root_cannot_be_moved_or_removed",
        2,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("RM", "/", ret=0),
            op("MV", "/", "/a", ret=False),
            op("READ_FILE", "/f", ret="x"),
            op("LS", "/", ret=["f"]),
        ],
        tags=["edge-values", "rejection", "remove", "move"],
    ),
    case(
        "l2_rm_a_single_file",
        2,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/f", "x", ret=True),
            op("RM", "/d/f", ret=1),
            op("LS", "/d", ret=[]),
            op("RM", "/d/f", ret=0),
        ],
        tags=["remove"],
    ),
    case(
        "l2_find_only_matches_the_last_component",
        2,
        [
            op("MKDIR", "/ab", ret=True),
            op("CREATE_FILE", "/ab/b", "1", ret=True),
            op("CREATE_FILE", "/b", "2", ret=True),
            op("FIND", "/", "b", ret=["/ab/b", "/b"]),
            op("FIND", "/", "ab", ret=["/ab"], why="not /ab/b, whose last component is b"),
        ],
        tags=["search", "edge-values"],
    ),
    case(
        "l2_find_is_case_sensitive",
        2,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/T", "up", ret=True),
            op("CREATE_FILE", "/d/t", "low", ret=True),
            op("FIND", "/", "t", ret=["/d/t"]),
            op("FIND", "/", "T", ret=["/d/T"]),
        ],
        tags=["search", "edge-values"],
    ),
    case(
        "l2_find_from_a_file_or_a_missing_path",
        2,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("FIND", "/nope", "f", ret=[]),
            op("FIND", "/f", "f", ret=["/f"], why="a file is at-or-below itself"),
            op("FIND", "/f", "other", ret=[]),
        ],
        tags=["search", "edge-values"],
    ),
    case(
        "l2_mv_to_a_name_that_extends_the_source",
        2,
        [
            op("MKDIR", "/a", ret=True),
            op("CREATE_FILE", "/a/f", "x", ret=True),
            op("MV", "/a", "/ab", ret=True, why="/ab is not inside /a"),
            op("READ_FILE", "/ab/f", ret="x"),
            op("LS", "/", ret=["ab"]),
        ],
        tags=["move", "cycles", "edge-values"],
    ),
    case(
        "l2_mv_a_file_to_a_deeper_name",
        2,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a/b", ret=True),
            op("CREATE_FILE", "/f", "x", ret=True),
            op("MV", "/f", "/a/b/f", ret=True),
            op("READ_FILE", "/a/b/f", ret="x"),
            op("FIND", "/", "f", ret=["/a/b/f"]),
        ],
        tags=["move", "nesting"],
    ),
    case(
        "l2_level1_still_works",
        2,
        [
            op("MKDIR", "/d", ret=True),
            op("MKDIR", "/d", ret=False),
            op("CREATE_FILE", "/d/f", "1", ret=True),
            op("READ_FILE", "/d/f", ret="1"),
            op("LS", "/d", ret=["f"]),
            op("MV", "/d", "/e", ret=True),
            op("LS", "/e", ret=["f"]),
            op("MKDIR", "/d", ret=True, why="the old name is free again"),
            op("READ_FILE", "/e/f", ret="1"),
        ],
        tags=["regression"],
    ),
]


# ==========================================================================
# Level 3
# ==========================================================================

LEVEL_3 = [
    case(
        "l3_a_grant_reaches_the_whole_subtree",
        3,
        [
            op("MKDIR", "/home", ret=True),
            op("MKDIR", "/home/u", ret=True),
            op("CREATE_FILE", "/home/u/f", "secret", ret=True),
            op("READ_FILE_AS", "bob", "/home/u/f", ret=None, why="nobody starts with permissions"),
            op("CHMOD", "/home", "bob", "r", ret=True),
            op("READ_FILE_AS", "bob", "/home/u/f", ret="secret"),
            op(
                "READ_FILE",
                "/home/u/f",
                ret="secret",
                why="the level-1 operation is never permission-checked",
            ),
        ],
        tags=["permissions", "inheritance", "admin"],
        visible=True,
        doc="A grant on a directory reaches everything below it.",
    ),
    case(
        "l3_a_deeper_grant_replaces_the_ancestors",
        3,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/a/b", ret=True),
            op("CREATE_FILE", "/a/f", "top", ret=True),
            op("CREATE_FILE", "/a/b/f", "inner", ret=True),
            op("CHMOD", "/a", "bob", "r", ret=True),
            op("CHMOD", "/a/b", "bob", "", ret=True),
            op("READ_FILE_AS", "bob", "/a/f", ret="top"),
            op(
                "READ_FILE_AS",
                "bob",
                "/a/b/f",
                ret=None,
                why="the empty grant on /a/b overrides the r on /a",
            ),
        ],
        tags=["permissions", "inheritance", "revocation"],
        visible=True,
        doc="The deepest grant on the path wins, even when it grants nothing.",
    ),
    case(
        "l3_create_needs_write_on_the_parent",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE_AS", "bob", "/d/f", "x", ret=False),
            op("CHMOD", "/d", "bob", "w", ret=True),
            op("CREATE_FILE_AS", "bob", "/d/f", "x", ret=True),
            op("READ_FILE", "/d/f", ret="x"),
            op("READ_FILE_AS", "bob", "/d/f", ret=None, why="w is not r"),
        ],
        tags=["permissions"],
        visible=True,
        doc="Writing needs w on the parent directory; reading still needs r.",
    ),
    case(
        "l3_rm_as_is_all_or_nothing",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("MKDIR", "/d/sub", ret=True),
            op("CREATE_FILE", "/d/a", "1", ret=True),
            op("CREATE_FILE", "/d/sub/b", "2", ret=True),
            op("CHMOD", "/d", "bob", "w", ret=True),
            op("CHMOD", "/d/sub/b", "bob", "", ret=True),
            op("RM_AS", "bob", "/d", ret=0, why="one entry is not writable, so nothing goes"),
            op("READ_FILE", "/d/a", ret="1", why="the refused removal left everything"),
            op("CHMOD", "/d/sub/b", "bob", "w", ret=True),
            op("RM_AS", "bob", "/d", ret=2),
            op("LS", "/", ret=[]),
        ],
        tags=["permissions", "atomicity", "subtree"],
        visible=True,
        doc="RM_AS needs write on everything it would remove, or it removes nothing.",
    ),
    case(
        "l3_a_grant_travels_with_a_moved_directory",
        3,
        [
            op("MKDIR", "/a", ret=True),
            op("MKDIR", "/b", ret=True),
            op("CREATE_FILE", "/a/f", "x", ret=True),
            op("CHMOD", "/a", "bob", "r", ret=True),
            op("MV", "/a", "/b/a", ret=True),
            op(
                "READ_FILE_AS",
                "bob",
                "/b/a/f",
                ret="x",
                why="permissions belong to the entry, so they move with it",
            ),
            op("FIND", "/", "f", ret=["/b/a/f"]),
        ],
        tags=["permissions", "move", "inheritance"],
        visible=True,
        doc="A grant is attached to the entry, not to the path string.",
    ),
    case(
        "l3_chmod_on_a_missing_path",
        3,
        [
            op("CHMOD", "/nope", "bob", "rw", ret=False),
            op("MKDIR", "/a", ret=True),
            op("CHMOD", "/a", "bob", "rw", ret=True),
        ],
        tags=["permissions", "rejection"],
    ),
    case(
        "l3_users_are_independent",
        3,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("CHMOD", "/f", "bob", "r", ret=True),
            op("READ_FILE_AS", "bob", "/f", ret="x"),
            op("READ_FILE_AS", "eve", "/f", ret=None),
        ],
        tags=["permissions"],
    ),
    case(
        "l3_perms_order_does_not_matter",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/f", "x", ret=True),
            op("CHMOD", "/d", "bob", "wr", ret=True),
            op("READ_FILE_AS", "bob", "/d/f", ret="x"),
            op("CREATE_FILE_AS", "bob", "/d/g", "y", ret=True),
        ],
        tags=["permissions", "edge-values"],
    ),
    case(
        "l3_a_later_grant_replaces_the_earlier_one",
        3,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("CHMOD", "/f", "bob", "rw", ret=True),
            op("READ_FILE_AS", "bob", "/f", ret="x"),
            op("CHMOD", "/f", "bob", "w", ret=True),
            op("READ_FILE_AS", "bob", "/f", ret=None, why="rw was replaced, not added to"),
        ],
        tags=["permissions", "revocation"],
    ),
    case(
        "l3_create_as_still_obeys_the_level1_rules",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/f", "old", ret=True),
            op("CHMOD", "/d", "bob", "rw", ret=True),
            op("CREATE_FILE_AS", "bob", "/d/f", "new", ret=False, why="the name is taken"),
            op("READ_FILE_AS", "bob", "/d/f", ret="old"),
            op("CREATE_FILE_AS", "bob", "/nope/f", "x", ret=False),
        ],
        tags=["permissions", "rejection"],
    ),
    case(
        "l3_rm_as_needs_write_on_the_path_itself",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/a", "1", ret=True),
            op("CHMOD", "/d/a", "bob", "w", ret=True),
            op("RM_AS", "bob", "/d", ret=0, why="/d itself is not writable"),
            op("RM_AS", "bob", "/d/a", ret=1),
            op("LS", "/d", ret=[]),
        ],
        tags=["permissions", "atomicity"],
    ),
    case(
        "l3_rm_as_on_an_empty_directory",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CHMOD", "/d", "bob", "w", ret=True),
            op("RM_AS", "bob", "/d", ret=0),
            op("LS", "/", ret=[], why="0 files removed, but the directory is gone"),
            op("RM_AS", "bob", "/nope", ret=0),
        ],
        tags=["permissions", "remove", "edge-values"],
    ),
    case(
        "l3_admin_operations_bypass_permissions",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/f", "x", ret=True),
            op("CHMOD", "/d", "bob", "", ret=True),
            op("READ_FILE", "/d/f", ret="x"),
            op("RM", "/d", ret=1, why="RM is administrative"),
        ],
        tags=["admin", "permissions"],
    ),
    case(
        "l3_a_grant_on_root_covers_paths_made_later",
        3,
        [
            op("CHMOD", "/", "bob", "rw", ret=True),
            op("MKDIR", "/a", ret=True),
            op("CREATE_FILE", "/a/f", "x", ret=True),
            op(
                "READ_FILE_AS",
                "bob",
                "/a/f",
                ret="x",
                why="the grant covers the subtree, including entries added afterwards",
            ),
            op("CREATE_FILE_AS", "bob", "/a/g", "y", ret=True),
        ],
        tags=["permissions", "inheritance"],
    ),
    case(
        "l3_levels_1_and_2_still_work",
        3,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/a", "1", ret=True),
            op("CREATE_FILE", "/d/a", "2", ret=False),
            op("LS", "/d", ret=["a"]),
            op("FIND", "/", "a", ret=["/d/a"]),
            op("MV", "/d", "/e", ret=True),
            op("RM", "/e", ret=1),
            op("LS", "/", ret=[]),
        ],
        tags=["regression"],
    ),
]


# ==========================================================================
# Level 4
# ==========================================================================

LEVEL_4 = [
    case(
        "l4_symlink_and_resolve",
        4,
        [
            op("MKDIR", "/real", ret=True),
            op("CREATE_FILE", "/real/f", "content", ret=True),
            op("SYMLINK", "/link", "/real", ret=True),
            op("RESOLVE", "/link", ret="/real"),
            op("RESOLVE", "/link/f", ret="/real/f"),
            op("READ_FILE", "/link/f", ret="content", why="a link mid-path is followed"),
            op("LS", "/link", ret=["f"]),
            op("RESOLVE", "/real/f", ret="/real/f"),
        ],
        tags=["symlinks", "resolution"],
        visible=True,
        doc="A link stands in for its target when a path is read through it.",
    ),
    case(
        "l4_reads_follow_a_trailing_link_but_moves_do_not",
        4,
        [
            op("CREATE_FILE", "/target", "T", ret=True),
            op("SYMLINK", "/link", "/target", ret=True),
            op("READ_FILE", "/link", ret="T", why="READ_FILE follows a trailing link"),
            op("MV", "/link", "/moved", ret=True, why="MV moves the link, not the target"),
            op("READ_FILE", "/target", ret="T"),
            op("READ_FILE", "/moved", ret="T"),
            op("LS", "/", ret=["moved", "target"]),
        ],
        tags=["resolution", "move"],
        visible=True,
        doc="The last component is followed when reading and not when moving.",
    ),
    case(
        "l4_rm_removes_the_link_not_the_target",
        4,
        [
            op("CREATE_FILE", "/target", "T", ret=True),
            op("SYMLINK", "/link", "/target", ret=True),
            op("RM", "/link", ret=0, why="a link is not a file, so nothing is counted"),
            op("READ_FILE", "/target", ret="T"),
            op("LS", "/", ret=["target"]),
        ],
        tags=["resolution", "remove"],
        visible=True,
        doc="Removing a link leaves the target alone, and counts no files.",
    ),
    case(
        "l4_loops_and_dangling_links_resolve_to_nothing",
        4,
        [
            op("SYMLINK", "/a", "/b", ret=True),
            op("SYMLINK", "/b", "/a", ret=True),
            op("RESOLVE", "/a", ret=None, why="the two links point at each other"),
            op("READ_FILE", "/a", ret=None),
            op("LS", "/a", ret=[]),
            op("SYMLINK", "/d", "/nowhere", ret=True),
            op("RESOLVE", "/d", ret=None, why="the target does not exist"),
            op("READ_FILE", "/d", ret=None),
        ],
        tags=["loops", "dangling", "resolution"],
        visible=True,
        doc="An unresolvable path is nothing, not an error.",
    ),
    case(
        "l4_find_does_not_descend_into_links",
        4,
        [
            op("MKDIR", "/real", ret=True),
            op("CREATE_FILE", "/real/f", "x", ret=True),
            op("SYMLINK", "/link", "/real", ret=True),
            op("FIND", "/", "f", ret=["/real/f"], why="FIND walks the real tree only"),
            op("FIND", "/", "link", ret=["/link"], why="the link itself is an entry"),
        ],
        tags=["resolution", "search"],
        visible=True,
        doc="FIND sees a link as one entry and does not walk through it.",
    ),
    case(
        "l4_symlink_creation_rules",
        4,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("SYMLINK", "/f", "/other", ret=False, why="something is already there"),
            op("SYMLINK", "/nope/l", "/f", ret=False),
            op("SYMLINK", "/l", "/f", ret=True),
            op("SYMLINK", "/l", "/f", ret=False),
            op("READ_FILE", "/f", ret="x"),
        ],
        tags=["symlinks", "rejection"],
    ),
    case(
        "l4_creating_through_a_directory_link",
        4,
        [
            op("MKDIR", "/real", ret=True),
            op("SYMLINK", "/link", "/real", ret=True),
            op("CREATE_FILE", "/link/new", "n", ret=True),
            op("READ_FILE", "/real/new", ret="n", why="the link mid-path was followed"),
            op("MKDIR", "/link/sub", ret=True),
            op("LS", "/real", ret=["new", "sub"]),
        ],
        tags=["resolution", "symlinks"],
    ),
    case(
        "l4_a_chain_of_links",
        4,
        [
            op("CREATE_FILE", "/target", "T", ret=True),
            op("SYMLINK", "/b", "/target", ret=True),
            op("SYMLINK", "/a", "/b", ret=True),
            op("RESOLVE", "/a", ret="/target"),
            op("READ_FILE", "/a", ret="T"),
        ],
        tags=["resolution", "symlinks"],
    ),
    case(
        "l4_a_link_to_a_file_cannot_be_traversed",
        4,
        [
            op("CREATE_FILE", "/f", "x", ret=True),
            op("SYMLINK", "/l", "/f", ret=True),
            op("RESOLVE", "/l/deeper", ret=None),
            op("READ_FILE", "/l/deeper", ret=None),
            op("CREATE_FILE", "/l/deeper", "y", ret=False),
        ],
        tags=["resolution", "edge-values"],
    ),
    case(
        "l4_removing_the_target_leaves_the_link_dangling",
        4,
        [
            op("CREATE_FILE", "/t", "T", ret=True),
            op("SYMLINK", "/l", "/t", ret=True),
            op("READ_FILE", "/l", ret="T"),
            op("RM", "/t", ret=1),
            op("RESOLVE", "/l", ret=None),
            op("READ_FILE", "/l", ret=None),
            op("LS", "/", ret=["l"], why="the link entry is still there"),
        ],
        tags=["dangling", "resolution", "remove"],
    ),
    case(
        "l4_permissions_attach_to_the_real_path",
        4,
        [
            op("MKDIR", "/real", ret=True),
            op("CREATE_FILE", "/real/f", "secret", ret=True),
            op("SYMLINK", "/link", "/real", ret=True),
            op("CHMOD", "/link", "bob", "r", ret=True, why="CHMOD follows a trailing link"),
            op("READ_FILE_AS", "bob", "/real/f", ret="secret"),
            op("READ_FILE_AS", "bob", "/link/f", ret="secret"),
        ],
        tags=["resolution", "permissions"],
    ),
    case(
        "l4_moving_a_directory_link_leaves_the_target",
        4,
        [
            op("MKDIR", "/real", ret=True),
            op("CREATE_FILE", "/real/f", "x", ret=True),
            op("MKDIR", "/d", ret=True),
            op("SYMLINK", "/link", "/real", ret=True),
            op("MV", "/link", "/d/link", ret=True),
            op("READ_FILE", "/d/link/f", ret="x"),
            op("LS", "/real", ret=["f"]),
            op("LS", "/", ret=["d", "real"]),
        ],
        tags=["resolution", "move"],
    ),
    case(
        "l4_resolve_on_ordinary_paths",
        4,
        [
            op("RESOLVE", "/", ret="/"),
            op("RESOLVE", "/nope", ret=None),
            op("MKDIR", "/a", ret=True),
            op("RESOLVE", "/a", ret="/a"),
            op("CREATE_FILE", "/a/f", "x", ret=True),
            op("RESOLVE", "/a/f", ret="/a/f"),
        ],
        tags=["resolution", "edge-values"],
    ),
    case(
        "l4_rm_of_a_directory_does_not_count_links",
        4,
        [
            op("MKDIR", "/d", ret=True),
            op("CREATE_FILE", "/d/f", "x", ret=True),
            op("SYMLINK", "/d/l", "/d/f", ret=True),
            op("RM", "/d", ret=1, why="one file and one link; links are not files"),
            op("LS", "/", ret=[]),
        ],
        tags=["remove", "resolution"],
    ),
    case(
        "l4_all_levels_together",
        4,
        [
            op("MKDIR", "/srv", ret=True),
            op("MKDIR", "/srv/data", ret=True),
            op("CREATE_FILE", "/srv/data/a.txt", "A", ret=True),
            op("CREATE_FILE", "/srv/data/b.txt", "B", ret=True),
            op("SYMLINK", "/current", "/srv/data", ret=True),
            op("READ_FILE", "/current/a.txt", ret="A"),
            op("LS", "/current", ret=["a.txt", "b.txt"]),
            op("CHMOD", "/srv", "bob", "r", ret=True),
            op("READ_FILE_AS", "bob", "/current/b.txt", ret="B"),
            op("CHMOD", "/srv/data/b.txt", "bob", "", ret=True),
            op("READ_FILE_AS", "bob", "/current/b.txt", ret=None),
            op("FIND", "/", "a.txt", ret=["/srv/data/a.txt"]),
            op("MV", "/srv/data", "/srv/archive", ret=True),
            op("RESOLVE", "/current", ret=None, why="the link still names the old path"),
            op("READ_FILE", "/srv/archive/a.txt", ret="A"),
            op(
                "READ_FILE_AS",
                "bob",
                "/srv/archive/a.txt",
                ret="A",
                why="bob's grant on /srv still covers it",
            ),
            op("READ_FILE_AS", "bob", "/srv/archive/b.txt", ret=None),
            op("RM", "/srv", ret=2),
        ],
        tags=["regression", "resolution", "permissions", "move", "search"],
    ),
]


ALL_CASES = tuple(LEVEL_1 + LEVEL_2 + LEVEL_3 + LEVEL_4)
